module: CloudConfiguration
author: IBM
github_url: https://github.com/IBM-Swift/CloudConfiguration/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, CloudConfiguration.xcodeproj, -target, CloudConfiguration, LIBRARY_SEARCH_PATHS=.build/debug]
