app:
  image: ibmcom/swift-ubuntu:3.1.1
  volumes:
    - .:/CloudEnvironment
  command: bash -c "cd /CloudEnvironment && swift -version && swift package clean && swift build && swift test && swift package clean"
